version: '3'
services:

  flask:
    build:
      context: .
    container_name: audioserver
    ports:
      - "4000:4000"
    expose:
      - 4000
    env_file:
      - sample.env
    links:
      - mongodb

  nginx:
    image: nginx:1.19.6-alpine
    container_name : nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - flask
  mongodb:
    container_name: mongodb
    ports:
      - "27017:27017"
    image: mongo:latest
    environment:
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - "mongodb-data:/data/db"
  # mongoclient:
  #   container_name: mongoclient
  #   ports:
  #     - "4000:3000"
  #   image: mongoclient/mongoclient:latest

volumes:
  mongodb-data: {}
