version: '3'
services:
  ## Router
  router01:
    image: mongo:4.4
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongo:/scripts
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.11
  router02:
    image: mongo:4.4
    container_name: router-02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts/mongo:/scripts
    ports:
      - 27018:27017
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.12
    links:
      - router01

  ## Config Servers
  configsvr01:
    image: mongo:4.4
    container_name: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet rs-config-server --dbpath /data/db
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/configsvr01:/data/db
    ports:
      - 27019:27017
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.13
    links:
      - shard01-a
      - shard02-a
      - shard03-a
  configsvr02:
    image: mongo:4.4
    container_name: mongo-config-02
    command: mongod --port 27017 --configsvr --replSet rs-config-server --dbpath /data/db
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/configsvr02:/data/db
    ports:
      - 27020:27017
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.14
    links:
      - configsvr01
  configsvr03:
    image: mongo:4.4
    container_name: mongo-config-03
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/configsvr03:/data/db
    ports:
      - 27021:27017
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.15
    links:
      - configsvr02

  ## Shards
  ## Shards 01

  shard01-a:
    image: mongo:4.4
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet shard01
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard01-a:/data/db
    ports:
      - 27022:27017
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.16
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    image: mongo:4.4
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet shard01
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard01-b:/data/db
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.17
    ports:
      - 27023:27017
  shard01-c:
    image: mongo:4.4
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet shard01
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard01-c:/data/db
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.18
    ports:
      - 27024:27017

  ## Shards 02
  shard02-a:
    image: mongo:4.4
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet shard02
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard02-a:/data/db
    ports:
      - 27025:27017
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.19
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    image: mongo:4.4
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet shard02
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard02-b:/data/db
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.20
    ports:
      - 27026:27017
  shard02-c:
    image: mongo:4.4
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet shard02
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard02-c:/data/db
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.21
    ports:
      - 27027:27017

  ## Shards 03
  shard03-a:
    image: mongo:4.4
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet shard03
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard03-a:/data/db
    ports:
      - 27028:27017
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.22
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    image: mongo:4.4
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet shard03
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard03-b:/data/db
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.23
    ports:
      - 27029:27017
  shard03-c:
    image: mongo:4.4
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet shard03
    volumes:
      - ./scripts/mongo:/scripts
      - /mongo_cluster/shard03-c:/data/db
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.24
    ports:
      - 27030:27017

  flask-app:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/code
    depends_on:
      - redis
      - router01
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.25
  redis:
    image: redis
    container_name: cache
    networks:
      audioserver-dev-env:
        ipv4_address: 172.21.0.26
    ports:
      - 6379:6379

volumes:
  mongo_cluster:

networks:
  audioserver-dev-env:
    name: WebServerInfrastructure
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16