sh.enableSharding("AudioServer")
db.adminCommand({shardCollection: "AudioServer.Files", key: {_id: "hashed"}})
db.adminCommand({shardCollection: "AudioServer.Batches", key: {_id: "hashed"}})
db.adminCommand({shardCollection: "AudioServer.Uploads", key: {_id: "hashed"}})
rs.status()