name: docker-compose-actions-workflow
on: push
jobs:
  Build-AudioServer-Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Building application
        run: docker-compose build
      - name: Create app infrastructure
        run: docker-compose up -d
      - name: Stating process config mongodb servers
        run: docker exec configsvr01 sh -c "mongo < /scripts/init-configserver.js"
      - name: Stating config mongodb Sharding for shard01
        run: docker exec shard01-a sh -c "mongo < /scripts/init-shard01.js"
      - name: Stating config mongodb Sharding for shard02
        run: docker exec shard02-a sh -c "mongo < /scripts/init-shard02.js"
      - name: Stating config mongodb Sharding for shard03
        run: docker exec shard03-a sh -c "mongo < /scripts/init-shard03.js"
      - name: Stating config mongodb routers
        run: docker exec router01 sh -c "mongo < /scripts/init-router.js"
      - name: Stating process enable mongo db and collections
        run: docker exec router01 sh -c "mongo < /scripts/enable.js"

