name: docker-compose-actions-workflow
on: push
jobs:
  Build-AudioServer-Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building application
        run: docker-compose build
      - name: Create default.cong infrastructure
        run: docker-compose up -d
      - name: Wait Stage 1
        run: sleep 20
      - name: Stating process config mongodb servers
        run: docker-compose exec -T configsvr01 sh -c "mongo < /scripts/init-configserver.js"
      - name: Stating config mongodb Sharding for shard01
        run: docker-compose exec -T shard01-a sh -c "mongo < /scripts/init-shard01.js"
      - name: Stating config mongodb Sharding for shard02
        run: docker-compose exec -T shard02-a sh -c "mongo < /scripts/init-shard02.js"
      - name: Stating config mongodb Sharding for shard03
        run: docker-compose exec -T shard03-a sh -c "mongo < /scripts/init-shard03.js"
      - name: Wait Stage 2
        run: sleep 240
      - name: Stating config mongodb routers
        run: docker-compose exec -T router01 sh -c "mongo < /scripts/init-router.js"
      - name: Stating process enable mongo db and collections
        run: docker-compose exec -T router01 sh -c "mongo < /scripts/enable.js"
      - name: Verifying Replica set for shard01
        run: docker exec  -T -it shard-01-node-a bash -c "echo 'rs.status()' | mongo --port 27017"
      - name: Verifying Replica set for shard02
        run: docker exec  -T -it shard-02-node-a bash -c "echo 'rs.status()' | mongo --port 27017"
      - name: Verifying Replica set for shard03
        run: docker exec -T -it shard-03-node-a bash -c "echo 'rs.status()' | mongo --port 27017"
      - name: finish
        run: echo "Infrastructure successfully builded."

