name: docker-compose-actions-workflow
on: push
jobs:
  Build-AudioServer-Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building application
        run: docker-compose build
      - name: Create Application infrastructure
        run: docker-compose up -d
      - name: finish
        run: echo "Infrastructure successfully created."

